### ISSUE TITLE
I get an error when i run wrapper.py 

### ISSUE THREAD

**Issue by NikiTricky2** [tannerbohn/MindMap#3]
When i run wrapper.py i get:
```
Traceback (most recent call last):
  File "wrapper.py", line 249, in <module>
    sheets = get_sheet_list()
  File "wrapper.py", line 152, in get_sheet_list
    flines = os.listdir(settings.SRC_DIR+'/Sheets/')
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/Sheets/'
```

**Comment by tannerbohn** [comment]
Hey @NikiTricky2 , I believe this error is a result of trying to run the code on a Windows OS. As the README states, it is currently only build to run on Linux-based systems. If you figure out a fix, I could integrate it -- however I am currently busy working on more pressing projects :/
